// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpinbiwlbsyqtayqixea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaW5iaXdsYnN5cXRheXFpeGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDgwODUsImV4cCI6MjA2NjM4NDA4NX0.tkJCyIFYQsa6SX4stK6GYds4iCThJ7RzyX5k0x3Z6EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);